import sys
from pathlib import Path

import torch

from app.schemas.analysis import RawEvidence

HACKATHON_PATH = Path(__file__).parent.parent.parent.parent / "ikigai-hackathon"
sys.path.insert(0, str(HACKATHON_PATH))

from config import load_config
from model import DeepfakeClassifier, build_model, load_checkpoint
from preprocessing import initialize_face_detector
from inference import preprocess_video_for_inference, run_inference, analyze_video
from forensic_engine import analyze_frame_predictions


class DetectionService:
    """
    Bridge between the backend and the ML detection pipeline.

    Uses the ikigai-hackathon Phase 4 pipeline for real deepfake detection.
    """

    def __init__(self) -> None:
        """
        Initialize the detection service with the ML pipeline.
        """
        self.model_version = "xception-synthguard-v1"
        
        self.config = load_config(str(HACKATHON_PATH / "config.yaml"))
        
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        
        model_name = self.config["model"].get("name", "xception")
        self.model = build_model(
            model_name=model_name,
            pretrained=self.config["model"]["pretrained"],
            dropout=self.config["model"]["dropout"],
            num_classes=self.config["model"].get("num_classes", 2),
            device=self.device,
        )
        
        checkpoint_path = HACKATHON_PATH / self.config.get("inference", {}).get("checkpoint", "models/xception_best.pth")
        if checkpoint_path.exists():
            load_checkpoint(str(checkpoint_path), self.model, device=self.device)
        else:
            print(f"WARNING: Model checkpoint not found at {checkpoint_path}. Using random weights.")
        
        self.face_app = initialize_face_detector(self.config)

    def analyze(
        self,
        video_path: Path,
    ) -> RawEvidence:
        """
        Analyze one video and return raw forensic evidence.

        Parameters
        ----------
        video_path:
            Path to the uploaded video.

        Returns
        -------
        RawEvidence:
            Evidence generated by the ML pipeline.
        """
        result = analyze_video(
            video_path=video_path,
            config=self.config,
            model=self.model,
            face_app=self.face_app,
            device=self.device,
        )
        
        forensic_result_object = result["forensic_result"]
        forensic_dict = forensic_result_object.to_dict() if hasattr(forensic_result_object, "to_dict") else dict(forensic_result_object)
        frame_infos = result.get("frame_infos", [])
        video_metadata = result.get("video_metadata", {})
        robustness_results = result.get("robustness_results", {})
        
        usable_frames = [f for f in frame_infos if f.get("usable", False)]
        frame_scores = [
            {
                "frame_id": f["frame_index"],
                "timestamp": f["timestamp_seconds"],
                "score": f.get("score", 0.0),
                "face_quality": f.get("face_quality"),
                "weight": f.get("weight", f.get("face_quality")),
                "boundary_score": f.get("boundary_score"),
                "frequency_anomaly": f.get("frequency_anomaly"),
                "blink_naturalness": f.get("blink_naturalness"),
                "identity_similarity": f.get("identity_similarity"),
                "identity_drift": f.get("identity_drift"),
            }
            for f in usable_frames
        ]
        
        susp_segs = forensic_dict.get("suspicious_segments", [])
        suspicious_segments = [
            {"start": s["start"] if isinstance(s, dict) else s.start, "end": s["end"] if isinstance(s, dict) else s.end}
            for s in susp_segs
        ]
        
        face_qualities = [f.get("face_quality", 0.5) for f in usable_frames]
        avg_face_quality = sum(face_qualities) / len(face_qualities) if face_qualities else 0.5
        
        return RawEvidence(
            visual_score=forensic_dict.get("manipulation_score", 0.0),
            frequency_score=forensic_dict.get("mean_score", 0.0),
            boundary_score=forensic_dict.get("average_boundary_score") if forensic_dict.get("average_boundary_score") is not None else forensic_dict.get("manipulation_score", 0.0),
            temporal_score=1.0 - forensic_dict.get("consistency", 0.5),
            identity_score=forensic_dict.get("identity_drift_score") if forensic_dict.get("identity_drift_score") is not None else forensic_dict.get("reliability", 0.5),
            frame_scores=frame_scores,
            suspicious_segments=[SuspiciousSegment(start=s["start"], end=s["end"]) for s in suspicious_segments],
            usable_frames=forensic_dict.get("usable_frames", 0),
            face_quality=avg_face_quality,
            tracking_quality=forensic_dict.get("consistency", 0.5),
            video_quality=forensic_dict.get("frame_coverage", 0.5),
            pipeline_forensic_result=forensic_dict,
            pipeline_frame_infos=frame_infos,
            pipeline_video_metadata=video_metadata,
            pipeline_robustness_results=robustness_results,
        )
